### PR TITLE
Switch to kinto-http for Remote Settings requests

### PR DESCRIPTION
**Pull request by HarshitSohaney**
## Description

This PR deals with switching from using requests to kinto-http to communicate with the remote settings server.

## What this PR changes

- Add kinto_http as a new installation in requirements.txt
- switch from using requests to using a kinto-http client for operations like `get_record` `create_record`

## Tracking Bugs

- [ ] #184 

### Blocks
- [ ] #194

### CODE REVIEW

**Comment by HarshitSohaney** [comment]
Rebased with main since #192 was merged. This should be easier to review now!

**Review by artines1 — APPROVED** [review]
The patch looks good to me.

Have you tested it on the Dev/Stage server to see if the request review works as expected?

**Comment by HarshitSohaney** [comment]
> The patch looks good to me.
> 
> Have you tested it on the Dev/Stage server to see if the request review works as expected?

I tested with the Dev server, but didn't want to mess with the stage server. I can run a test with stage right now

**Comment by HarshitSohaney** [comment]
> > The patch looks good to me.
> > Have you tested it on the Dev/Stage server to see if the request review works as expected?
> 
> I tested with the Dev server, but didn't want to mess with the stage server. I can run a test with stage right now

Done testing with Stage server, successfully requested review automatically!

**Pull request merged**
