### PR TITLE
Add adddel line to delete all previous chunks (fixes #8)

### LINKED ISSUE #8: send adddel range to delete old chunks
We need to send

ad:1-\<current_chunk_number - 1\>

in order to make sure clients don't keep appending new chunks.

### PR DESCRIPTION
**Pull request by monicachew**
@rtilder @rfk This should fix https://github.com/mozilla-services/shavar/issues/21 after it's deployed.

### CODE REVIEW

**Comment by monicachew** [comment]
@sjhworkman Are you OK with this change?

**Comment by sjhworkman** [comment]
Yes. Looks good to me.

**Comment by rtilder** [comment]
This effectively turns the shavar protocol into an HTTP GET request.  If that is what was desired why are we using the SafeBrowsing list format and protocol?  Should we just switch to a simple HTTPS request?  It would be significantly simpler on the operations side of the house than running an entirely separate service.

**Comment by monicachew** [comment]
@rtilder We used SafeBrowsing to be able to support better incremental updates in the future, although  there's a lot of logic missing server side (in terms of both generating chunks and computing deltas) to take advantage of that.

At this point it would be a major client side change to switch away from the protocol.

**Comment by rtilder** [comment]
The server shouldn't compute the deltas or generate chunks.  That should be done when each list update is generated since deltas are applied to the list data and not to individual clients.  While probably not quite a quick fix to implement, delta generation shouldn't be too much additional work to do against the change history of the published list data.

**Pull request merged**
