### PR TITLE
Remove references to Disconnect category and disconnect_mapping.json

### LINKED ISSUE #118: Remove Disconnect and Google mapping references
# About this Issue
As mentioned in this [issue](https://github.com/mozilla-mobile/firefox-ios/issues/5968) we are not longer using `google-mapping.json`. Also, since we applied all the mapping for Disconnect category since [this pr](https://github.com/mozilla-services/shavar-prod-lists/pull/110), we can now remove all the references to `google-mapping.json`, Disconnect category, and `disconnect-mapping.json`

# Acceptance Criteria
- [ ] Remove all the references to `google-mapping.json`
- [ ] Remove all the references to Disconnect category. See https://github.com/mozilla-services/shavar-list-creation/issues/126 for more details
- [x] Remove all the references to `disconnect-mapping.json`
- [x] Remove all references to Disconnect category in [config](https://github.com/mozilla-services/shavar-list-creation-config/)

### PR DESCRIPTION
**Pull request by boolean5**
This PR closes #118 by removing all references to the Disconnect category and to `disconnect_mapping.json`.

### CODE REVIEW

**Comment by boolean5** [comment]
@skim1102, @englehardt, should I also remove the `disconnect_mapping.json` file itself or is it still
used by other services?

Also, I noticed that the blocklists in https://github.com/mozilla-services/shavar-experiments are still using the Disconnect category. As a result the corresponding created lists  (`fastblock1-track-digest256`, `fastblock2-track-digest256` and `fastblock3-track-digest256`) now contain fewer domains than before. Should we wait for the fastblock blocklists to be updated before merging this PR?

**Comment by skim1102** [comment]
> Also, I noticed that the blocklists in https://github.com/mozilla-services/shavar-experiments are still using the Disconnect category. As a result, the corresponding created lists (`fastblock1-track-digest256`, `fastblock2-track-digest256` and `fastblock3-track-digest256`) now contain fewer domains than before. Should we wait for the fastblock blocklists to be updated before merging this PR?

@englehardt, as @boolean5, the fastblock lists do indeed have Disconnect in its json files, see this [fastblock1.json example](https://github.com/mozilla-services/shavar-experiments/blob/master/fastblock1.json#L8768). It seems the last time [shavar-experiments](https://github.com/mozilla-services/shavar-experiments) was updated 2 years ago (1yr ago for CODE_OF_CONDUCT). Can we remove the fastblock from shavar-list-creation? Or should we update the shavar-experiments to no longer use the `Disconnect` category like we did on shavar-prod-lists?

**Comment by skim1102** [comment]
> @skim1102, @englehardt, should I also remove the `disconnect_mapping.json` file itself or is it still
> used by other services?

@boolean5, we should keep the `disconnect-mapping.json` for now to ensure other components (iOS or Android) no longer uses/references the file. I will update the issue once I find out.

**Comment by englehardt** [comment]
> @englehardt, as @boolean5 mentioned, the fastblock lists do indeed have Disconnect in its json files, see this fastblock1.json example. It seems the last time shavar-experiments was updated 2 years ago (1yr ago for CODE_OF_CONDUCT). Can we remove the fastblock from shavar-list-creation? Or should we update the shavar-experiments to no longer use the Disconnect category like we did on shavar-prod-lists?

Yes we can remove the Fastblock lists.

**Comment by boolean5** [comment]
> Yes we can remove the Fastblock lists.

I added a commit that removes them. Thanks for clarifying this. Should we also remove the Fastblock lists from https://github.com/mozilla-services/shavar-list-creation-config/ before merging this?

**Comment by skim1102** [comment]
@boolean5, yes. Along with that in config repo for shavar-list-creation we should also remove all refernces to Disconnect category in Stage and Prod .ini files.

**Comment by boolean5** [comment]
After [discussing](https://github.com/mozilla-services/shavar-list-creation/issues/118#issuecomment-599815037) this with @skim1102, I'm pushing a commit that removes the `disconnect_mapping.json` file.

**Comment by boolean5** [comment]
> @boolean5, yes. Along with that in config repo for shavar-list-creation we should also remove all refernces to Disconnect category in Stage and Prod .ini files.

I just submitted a PR for this: https://github.com/mozilla-services/shavar-list-creation-config/pull/60

**Comment by boolean5** [comment]
While working on this I noticed that the deprecated Disconnect category is still present in https://github.com/mozilla-services/shavar-staging-lists/blob/master/disconnect-blacklist.json and https://github.com/mozilla-services/shavar-test-lists/blob/master/track.json. These lists are probably not actively used right know but I thought I'd mention it here in case they need to be updated.

**Comment by skim1102** [comment]
> While working on this I noticed that the deprecated Disconnect category is still present in https://github.com/mozilla-services/shavar-staging-lists/blob/master/disconnect-blacklist.json and https://github.com/mozilla-services/shavar-test-lists/blob/master/track.json. These lists are probably not actively used right now but I thought I'd mention it here in case they need to be updated.

@boolean5, thanks for bringing these up. Can you create an issue on shavar-list-creation to start documenting whether the repositories are being used or referenced anywhere?

**Comment by skim1102** [comment]
@boolean5, from my previous experiences I do not merge after 4:30PM my local time to save myself from the potential issues caused by the "5PM push". As a result, I will merge this first thing tomorrow!

**Comment by skim1102** [comment]
Screen Shot 2020-03-19 at 4 42 47 PM
Shucks, I cannot merge this unless all the commits are signed. Can you sign the commits?

**Comment by boolean5** [comment]
Sure, I signed the commits and rebased them on the current master.

**Comment by boolean5** [comment]
> Can you create an issue on shavar-list-creation to start documenting whether the repositories are being used or referenced anywhere?

Done! I opened the issue here: https://github.com/mozilla-services/shavar-list-creation/issues/126

**Comment by boolean5** [comment]
I noticed that `category_domains.py` in https://github.com/mozilla-services/shavar-prod-lists/pull/156 is planning to use `disconnect_mapping.json` to compare shavar-prod-lists and disconnect-tracking-protection lists. I see two options now:
1. Removing from this PR the commit that removes the `disconnect_mapping.json` file.
2. Keeping this PR as it is and moving `disconnect_mapping.json` to shavar-prod-lists, which is the only repo using it. This has been discussed before in https://github.com/mozilla-mobile/firefox-ios/issues/5968#issuecomment-574434964 and seems like a good idea.

@skim1102, what do you think?

**Comment by skim1102** [comment]
@boolean5 since we are going to be removing that file I do not think we should move the file. I left a comment to remove references to `disconnect_mapping.json`

**Pull request merged**
