### PR TITLE
Add remote settings config check

### PR DESCRIPTION
**Pull request by skim1102**
# About this PR
- [ ] Adding some default configuration for Remote Settings in case the `-config` repo is not updated with the Remote Settings config
- [ ] Graceful returns and logging for various errors surrounding config missing or be incorrect

### CODE REVIEW

**Comment by groovecoder** [comment]
Need to also cover the ones that aren't pulled from environment variables?

```
Traceback (most recent call last):
  File "./lists2safebrowsing.py", line 31, in <module>
    from publish2cloud import (
  File "/Users/lcrouch/code/mozilla-services/shavar-list-creation/publish2cloud.py", line 24, in <module>
    REMOTE_SETTINGS_BUCKET = CONFIG.get('main', 'remote_settings_bucket')
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ConfigParser.py", line 618, in get
    raise NoOptionError(option, section)
ConfigParser.NoOptionError: No option 'remote_settings_bucket' in section: 'main'
```

**Comment by groovecoder** [comment]
(When I deleted *all* the `remote_settings` lines from the `.ini` file.)

**Comment by groovecoder** [comment]
Oops, I forgot to change to this branch.

**Comment by skim1102** [comment]
@groovecoder the reason why currently in staging we are getting `Upload to Remote Setting and S3 disabled.`
In my code [here](https://github.com/skim1102/shavar-list-creation/blob/add-remote-settings-config-check/publish2cloud.py#L239):
```
        upload_to_s3 = False
        if (config.has_option(section, 's3_upload')
                and config.getboolean(section, 's3_upload')):
            upload_to_s3 = True
```
I presumed that `upload_to_s3` is `False` unless config is specified.
However, if you look at the code before my PRs it assumes that the `upload_to_s3` is `True` unless config is specified as seen [here](https://github.com/skim1102/shavar-list-creation/blob/master/lists2safebrowsing.py#L646):
```
        if (config.has_option(section, "s3_upload")
                and not config.getboolean(section, "s3_upload")):
            print("Skipping S3 upload for %s" % section)
            continue```

My suggested fix is:
```
        upload_to_s3 = True
        if (config.has_option(section, 's3_upload')
                and not config.getboolean(section, 's3_upload')):
            upload_to_s3 = False
```
WDYT?

**Comment by groovecoder** [comment]
Yeah, let's default `upload_to_s3` to `True` like the old code did so the job runs as expected. We can change (again) later.

**Pull request merged**
