### PR TITLE
(WIP, Do Not Merge) Bug 1425075 - config categories for each list

### PR DESCRIPTION
**Pull request by groovecoder**
Bug 1425075 - config categories for each list
sample ads, analytics, and social list configs
refactor a default_disconnect_url config

To deploy:
1. [ ] Merge this PR to add this new logic
2. [ ] Merge [`shavar-list-creation-config` PR](https://github.com/mozilla-services/shavar-list-creation-config/pull/25) adding the ads, analytics, and social
3. [ ] Test the resulting lists on the stage server
4. [ ] Send the same PR adding ads, analytics, and social configs to https://github.com/mozilla-services/shavar-list-creation-config/blob/master/prod.ini
5. [ ] Test the resulting lists on the prod server

### CODE REVIEW

**Comment by fmarier** [comment]
That approach looks good to me.

**Comment by groovecoder** [comment]
I fixed a bug and added sample configs for ads, analytics, and social category lists. Example output:
```
Tracking protection(tracking-protection-base): publishing 1797 items; file size 57526
Tracking protection(tracking-protection-baseeff): publishing 1 items; file size 51
Tracking protection(tracking-protection-basew3c): publishing 0 items; file size 18
Tracking protection(tracking-protection-content): publishing 514 items; file size 16470
Tracking protection(tracking-protection-contenteff): publishing 0 items; file size 18
Tracking protection(tracking-protection-contentw3c): publishing 0 items; file size 18
Tracking protection(tracking-protection-ads): publishing 1459 items; file size 46710
Tracking protection(tracking-protection-analytics): publishing 255 items; file size 8181
Tracking protection(tracking-protection-social): publishing 43 items; file size 1397
```

**Comment by ckolos** [comment]
repeating disconnect_url so many times in the config file makes me think that there's got to be a more efficient way to specify some of these parameters.

**Comment by groovecoder** [comment]
Refactored a new `main` `default_disconnect_url` config.

**Pull request merged**
